version = 0.1

[default.deploy.parameters]
stack_name = "document-processing-sam"
resolve_s3 = true
s3_prefix = "document-processing-sam"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
parameter_overrides = "NotificationEmail=\"creamcorn2@gmail.com\""
image_repositories = []

[default.global.parameters]
region = "us-east-1"
